Models/ErrorViewModel.cs
namespace Salao_De_Cabeleireiro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SalaoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Salao_De_Cabeleireiro.Models
{
    public class SalaoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o campo do Nome Cliente")]
        public string NomeCliente { get; set; }

        [Required(ErrorMessage = "Digite o campo do Nome Funcionário")]
        public string NomeFuncionario { get; set; }

        [Required(ErrorMessage = "Digite o campo do Tipo de Serviço")]
        public string Servico { get; set; }

        public DateTime Horario { get; set; } = DateTime.Now;
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Salao_De_Cabeleireiro.Models;
using System.Diagnostics;

namespace Salao_De_Cabeleireiro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SalaoController.cs
using Microsoft.AspNetCore.Mvc;
using Salao_De_Cabeleireiro.Data;
using Salao_De_Cabeleireiro.Models;
using System.Net.Http.Headers;

namespace Salao_De_Cabeleireiro.Controllers
{
    public class SalaoController : Controller
    {
        readonly private ApplicationDbContext _db;

        public SalaoController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<SalaoModel> salao = _db.Salao;
            return View(salao);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(SalaoModel salao)
        {
            if (ModelState.IsValid)
            {
                _db.Salao.Add(salao);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            SalaoModel salao = _db.Salao.FirstOrDefault(x => x.Id == id);

            if (salao == null)
            {
                return NotFound();
            }

            return View(salao);
        }

        [HttpPost]
        public IActionResult Editar(SalaoModel salao)
        {
            if (ModelState.IsValid)
            {
                _db.Salao.Update(salao);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(salao);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            SalaoModel salao = _db.Salao.FirstOrDefault(x => x.Id == id);

            if (salao == null)
            {
                return NotFound();
            }

            return View(salao);
        }

        [HttpPost]
        public IActionResult Excluir(SalaoModel salao)
        {
            if (salao == null)
            {
                return NotFound();
            }
            _db.Salao.Remove(salao);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Views/Dados/Cadastrar.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Cadastrar Dados do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Dados</h1>
    </div>
    <form method="post" asp-controller="Dados" asp-action="Cadastrar">
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Dados" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Dados/Editar.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Editar Dados do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Editar Dados</h1>
    </div>
    <form method="post" asp-controller="Dados" asp-action="Editar">
        <input type="hidden" asp-for="Id"/>
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Dados" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Dados/Excluir.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Excluir Dados do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir Dados</h1>
    </div>
    <form method="post" asp-controller="Dados" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" disabled id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" disabled id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" disabled id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Dados" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Dados/Index.cshtml
@model IEnumerable<SalaoModel>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Dados do Salão de Cabeleireiro</h1>
        <a class="btn btn-success mx-2" asp-controller="Dados" asp-action="Cadastrar">Cadastrar novo dado</a>
    </div>

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">NomeCliente</th>
                <th scope="col">NomeFuncionario</th>
                <th scope="col">Servico</th>
                <th scope="col">Horario</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var salao in Model)
                {
                    <tr>
                        <th scope="row">@salao.NomeCliente</th>
                        <td>@salao.NomeFuncionario</td>
                        <td>@salao.Servico</td>
                        <td>@salao.Horario</td>
                        <td>
                            <a asp-controller="Dados" asp-action="Editar" asp-route-id="@salao.Id" class="btn btn-warning mx-2">Editar</a>
                            <a asp-controller="Dados" asp-action="Excluir" asp-route-id="@salao.Id" class="btn btn-danger mx-2">Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Salao/Cadastrar.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Cadastrar Salao do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Salao</h1>
    </div>
    <form method="post" asp-controller="Salao" asp-action="Cadastrar">
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Salao" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Salao/Editar.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Editar Salao do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Editar Salao</h1>
    </div>
    <form method="post" asp-controller="Salao" asp-action="Editar">
        <input type="hidden" asp-for="Id"/>
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Salao" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Salao/Excluir.cshtml
@model SalaoModel
@{
    ViewData["title"] = "Excluir Salao do Salão";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir Salao</h1>
    </div>
    <form method="post" asp-controller="Salao" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label for="NomeCliente" class="text-light">Endereço de email</label>
            <input type="text" class="form-control" asp-for="NomeCliente" disabled id="NomeCliente" aria-describedby="emailHelp" placeholder="Nome do Cliente?" />
            <span class="text-danger" asp-validation-for="NomeCliente"></span>
        </div>
        <div class="form-group">
            <label for="NomeFuncionario" class="text-light">Nome do Funcionário</label>
            <input type="text" class="form-control" asp-for="NomeFuncionario" disabled id="NomeFuncionario" aria-describedby="emailHelp" placeholder="Nome do Funcionário?" />
            <span class="text-danger" asp-validation-for="NomeFuncionario"></span>
        </div>
        <div class="form-group">
            <label for="Servico" class="text-light">Serviço</label>
            <input type="text" class="form-control" asp-for="Servico" disabled id="Servico" aria-describedby="emailHelp" placeholder="Servico Prestado?" />
            <span class="text-danger" asp-validation-for="Servico"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Enviar</button>
            <a class="btn btn-primary w-50" asp-controller="Salao" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Salao/Index.cshtml
@model IEnumerable<SalaoModel>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Salao do Salão de Cabeleireiro</h1>
        <a class="btn btn-success mx-2" asp-controller="Salao" asp-action="Cadastrar">Cadastrar novo dado</a>
    </div>

    <table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">NomeCliente</th>
            <th scope="col">NomeFuncionario</th>
            <th scope="col">Servico</th>
            <th scope="col">Horario</th>
        </tr>
    </thead>
    <tbody>
            @if (Model != null)
            {
                @foreach (var salao in Model)
                {
                                <tr>
                                    <th scope="row">@salao.NomeCliente</th>
                                    <td>@salao.NomeFuncionario</td>
                                    <td>@salao.Servico</td>
                                    <td>@salao.Horario</td>
                                    <td>
                                        <a asp-controller="Salao" asp-action="Editar" asp-route-id="@salao.Id" class="btn btn-warning mx-2">Editar</a>
                                        <a asp-controller="Salao" asp-action="Excluir" asp-route-id="@salao.Id" class="btn btn-danger mx-2">Excluir</a>
                                    </td>
                                </tr>
                }
            }
    </tbody>
    </table>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Salao_De_Cabeleireiro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Salao_De_Cabeleireiro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Salao_De_Cabeleireiro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salao" asp-action="Index">Dados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Salao_De_Cabeleireiro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>